name: Flask App Tests

on: 
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubunutu-latest
        defaults:
            run:
                working-directory: ./app/
            
            
        strategy:
            matrix:
                python-version: [3.8]
        
        env:
            MODE: "dev"

        
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-pythion@v4
              with:
                python-version: ${{ matrix.python-version }}

            
